/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,js}'],
  theme: {
    extend: {
      colors: {
        fh: {
          bg:       '#0d1117',
          surface:  '#161b22',
          elevated: '#1c2128',
          overlay:  '#21262d',
          muted:    '#30363d',
          border:   '#30363d',
          'border-hover': '#484f58',
          text:     '#e6edf3',
          'text-secondary': '#8b949e',
          'text-muted': '#6e7681',
          accent:   '#58a6ff',
          'accent-emphasis': '#388bfd',
          'accent-subtle': '#58a6ff1a',
          green:    '#3fb950',
          'green-muted': '#238636',
          'green-subtle': '#3fb95015',
          red:      '#f85149',
          'red-muted': '#da3633',
          'red-subtle': '#f8514915',
          purple:   '#bc8cff',
          'purple-subtle': '#bc8cff15',
          yellow:   '#d29922',
          'yellow-subtle': '#d2992215',
          orange:   '#db6d28',
          cyan:     '#39d2c0',
          pink:     '#f778ba',
        },
      },
      fontFamily: {
        sans: ['IBM Plex Sans', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Noto Sans', 'Helvetica', 'Arial', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'SF Mono', 'Menlo', 'Consolas', 'Liberation Mono', 'monospace'],
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '0.875rem' }],
      },
      spacing: {
        '4.5': '1.125rem',
        '13': '3.25rem',
        '15': '3.75rem',
        '18': '4.5rem',
      },
      borderRadius: {
        'xl': '0.75rem',
        '2xl': '1rem',
      },
      backdropBlur: {
        xs: '2px',
      },
      animation: {
        'fade-in':        'fadeIn 0.2s ease-out forwards',
        'fade-out':       'fadeOut 0.2s ease-in forwards',
        'slide-up':       'slideUp 0.25s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slide-down':     'slideDown 0.25s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slide-in-right': 'slideInRight 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slide-in-left':  'slideInLeft 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'scale-in':       'scaleIn 0.2s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'shimmer':        'shimmer 1.5s ease-in-out infinite',
        'pulse-soft':     'pulseSoft 2s ease-in-out infinite',
        'spin-slow':      'spin 1.2s linear infinite',
        'glow-pulse':     'glowPulse 2s ease-in-out infinite',
        'progress-stripe':'progressStripe 1s linear infinite',
        'toast-enter':    'toastEnter 0.35s cubic-bezier(0.21, 1.02, 0.73, 1) forwards',
        'toast-exit':     'toastExit 0.2s ease-in forwards',
      },
      keyframes: {
        fadeIn:       { from: { opacity: '0' }, to: { opacity: '1' } },
        fadeOut:      { from: { opacity: '1' }, to: { opacity: '0' } },
        slideUp:      { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideDown:    { from: { opacity: '0', transform: 'translateY(-8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideInRight: { from: { opacity: '0', transform: 'translateX(16px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        slideInLeft:  { from: { opacity: '0', transform: 'translateX(-16px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        scaleIn:      { from: { opacity: '0', transform: 'scale(0.95)' }, to: { opacity: '1', transform: 'scale(1)' } },
        shimmer:      { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        pulseSoft:    { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.6' } },
        glowPulse:    { '0%, 100%': { boxShadow: '0 0 4px rgba(88,166,255,0.3)' }, '50%': { boxShadow: '0 0 12px rgba(88,166,255,0.5)' } },
        progressStripe: {
          '0%':   { backgroundPosition: '1rem 0' },
          '100%': { backgroundPosition: '0 0' },
        },
        toastEnter: {
          from: { opacity: '0', transform: 'translateY(12px) scale(0.96)' },
          to:   { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        toastExit: {
          from: { opacity: '1', transform: 'translateY(0) scale(1)' },
          to:   { opacity: '0', transform: 'translateY(8px) scale(0.96)' },
        },
      },
      boxShadow: {
        'fh':        '0 0 0 1px rgba(48,54,61,0.6)',
        'fh-md':     '0 4px 12px rgba(1,4,9,0.55)',
        'fh-lg':     '0 8px 24px rgba(1,4,9,0.75)',
        'fh-xl':     '0 12px 40px rgba(1,4,9,0.85)',
        'fh-inset':  'inset 0 1px 0 rgba(255,255,255,0.03)',
        'fh-glow':   '0 0 0 2px rgba(88,166,255,0.3)',
        'fh-glow-green': '0 0 0 2px rgba(63,185,80,0.3)',
        'fh-glow-red':   '0 0 0 2px rgba(248,81,73,0.3)',
        'fh-ring':   '0 0 0 3px rgba(88,166,255,0.15)',
      },
      transitionDuration: {
        '250': '250ms',
      },
      transitionTimingFunction: {
        'bounce-in': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [],
};
